### ISSUE TITLE
Leaflet 1.0 compatibility

### ISSUE THREAD

**Issue by adriennn** [umurgdk/leaflet-marker-menu#3]
Great plugin!
Are you planning to make this compatible with 1.0 in the near future? I get undefined 'call' and 'callback' types of error with 1.0 but I haven't looked into it more deeply.

**Comment by umurgdk** [comment]
@adriennn unfortunately not in a near future :/ but pull requests are welcome :)

**Comment by adriennn** [comment]
alright I'll look into it when I have a chance.
